name: Build
description: Setup JDK and build with Gradle
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: gradle
    - uses: gradle/actions/setup-gradle@v4
    - if: runner.os != 'Windows'
      shell: bash
      run: chmod +x gradlew
    - shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          ./gradlew.bat --no-daemon build
        else
          ./gradlew --no-daemon build
        fi
