name: Build
on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        java-version:
          - "21"
        distribution:
          - "temurin"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable on *nix
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build
        run: gradlew build

      - name: Build
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./gradlew.bat --no-daemon build
          else
            ./gradlew --no-daemon build
          fi

