name: Code Quality Checks

on:
  workflow_call:

jobs:
  check-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
      - run: ./gradlew check
