name: Code Quality Checks

on:
  workflow_call:

jobs:
  check-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ./gradlew check
