name: Run the Simulation
on:
  workflow_call:

jobs:
  run_simulation:
    name: Run Simulation
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        java-version:
          - "21"
        distribution:
          - "temurin"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle_build

      - name: Run for 5s (unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euo pipefail
          BIN="$(find . -type f -path '*/build/install/*/bin/*' -maxdepth 6 | head -n1)"
          test -n "$BIN" || { echo "No installed binary found"; exit 1; }
          chmod +x "$BIN"
          "$BIN" &
          PID=$!
          sleep 5
          kill "$PID" || true
          wait "$PID" || true

      - name: Run for 5s (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $bin = Get-ChildItem -Path . -Recurse -File -Filter * | Where-Object { $_.FullName -match '\\build\\install\\[^\\]+\\bin\\[^\\]+\.bat$' } | Select-Object -First 1
          if (-not $bin) { throw "No installed binary found" }
          $p = Start-Process -FilePath $bin.FullName -PassThru
          Start-Sleep -Seconds 5
          Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
