name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  code_quality_checks:
    uses: ./.github/actions/_code-quality-checks.yml
  run:
    uses: ./.github/actions/_run.yml
